server:
  port: 9300
spring:
  application:
    name: service-user
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userDB;
    driver-class-name: org.h2.Driver
    plataform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect